/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.fiberhome.nmpDataBusPlugin.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum FileState implements org.apache.thrift.TEnum {
  changed(1),
  created(2),
  deleted(3),
  renamed(4);

  private final int value;

  private FileState(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static FileState findByValue(int value) { 
    switch (value) {
      case 1:
        return changed;
      case 2:
        return created;
      case 3:
        return deleted;
      case 4:
        return renamed;
      default:
        return null;
    }
  }
}
