/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.fiberhome.nmpDataBusPlugin.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)", date = "2018-09-19")
public class Topology implements org.apache.thrift.TBase<Topology, Topology._Fields>, java.io.Serializable, Cloneable, Comparable<Topology> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("Topology");

  private static final org.apache.thrift.protocol.TField LINES_FIELD_DESC = new org.apache.thrift.protocol.TField("Lines", org.apache.thrift.protocol.TType.LIST, (short)1);
  private static final org.apache.thrift.protocol.TField NODES_FIELD_DESC = new org.apache.thrift.protocol.TField("Nodes", org.apache.thrift.protocol.TType.LIST, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new TopologyStandardSchemeFactory());
    schemes.put(TupleScheme.class, new TopologyTupleSchemeFactory());
  }

  public List<TopoLine> Lines; // required
  public List<TopoNode> Nodes; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    LINES((short)1, "Lines"),
    NODES((short)2, "Nodes");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // LINES
          return LINES;
        case 2: // NODES
          return NODES;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.LINES, new org.apache.thrift.meta_data.FieldMetaData("Lines", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, TopoLine.class))));
    tmpMap.put(_Fields.NODES, new org.apache.thrift.meta_data.FieldMetaData("Nodes", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, TopoNode.class))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(Topology.class, metaDataMap);
  }

  public Topology() {
  }

  public Topology(
    List<TopoLine> Lines,
    List<TopoNode> Nodes)
  {
    this();
    this.Lines = Lines;
    this.Nodes = Nodes;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public Topology(Topology other) {
    if (other.isSetLines()) {
      List<TopoLine> __this__Lines = new ArrayList<TopoLine>(other.Lines.size());
      for (TopoLine other_element : other.Lines) {
        __this__Lines.add(new TopoLine(other_element));
      }
      this.Lines = __this__Lines;
    }
    if (other.isSetNodes()) {
      List<TopoNode> __this__Nodes = new ArrayList<TopoNode>(other.Nodes.size());
      for (TopoNode other_element : other.Nodes) {
        __this__Nodes.add(new TopoNode(other_element));
      }
      this.Nodes = __this__Nodes;
    }
  }

  public Topology deepCopy() {
    return new Topology(this);
  }

  @Override
  public void clear() {
    this.Lines = null;
    this.Nodes = null;
  }

  public int getLinesSize() {
    return (this.Lines == null) ? 0 : this.Lines.size();
  }

  public java.util.Iterator<TopoLine> getLinesIterator() {
    return (this.Lines == null) ? null : this.Lines.iterator();
  }

  public void addToLines(TopoLine elem) {
    if (this.Lines == null) {
      this.Lines = new ArrayList<TopoLine>();
    }
    this.Lines.add(elem);
  }

  public List<TopoLine> getLines() {
    return this.Lines;
  }

  public Topology setLines(List<TopoLine> Lines) {
    this.Lines = Lines;
    return this;
  }

  public void unsetLines() {
    this.Lines = null;
  }

  /** Returns true if field Lines is set (has been assigned a value) and false otherwise */
  public boolean isSetLines() {
    return this.Lines != null;
  }

  public void setLinesIsSet(boolean value) {
    if (!value) {
      this.Lines = null;
    }
  }

  public int getNodesSize() {
    return (this.Nodes == null) ? 0 : this.Nodes.size();
  }

  public java.util.Iterator<TopoNode> getNodesIterator() {
    return (this.Nodes == null) ? null : this.Nodes.iterator();
  }

  public void addToNodes(TopoNode elem) {
    if (this.Nodes == null) {
      this.Nodes = new ArrayList<TopoNode>();
    }
    this.Nodes.add(elem);
  }

  public List<TopoNode> getNodes() {
    return this.Nodes;
  }

  public Topology setNodes(List<TopoNode> Nodes) {
    this.Nodes = Nodes;
    return this;
  }

  public void unsetNodes() {
    this.Nodes = null;
  }

  /** Returns true if field Nodes is set (has been assigned a value) and false otherwise */
  public boolean isSetNodes() {
    return this.Nodes != null;
  }

  public void setNodesIsSet(boolean value) {
    if (!value) {
      this.Nodes = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case LINES:
      if (value == null) {
        unsetLines();
      } else {
        setLines((List<TopoLine>)value);
      }
      break;

    case NODES:
      if (value == null) {
        unsetNodes();
      } else {
        setNodes((List<TopoNode>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case LINES:
      return getLines();

    case NODES:
      return getNodes();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case LINES:
      return isSetLines();
    case NODES:
      return isSetNodes();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof Topology)
      return this.equals((Topology)that);
    return false;
  }

  public boolean equals(Topology that) {
    if (that == null)
      return false;

    boolean this_present_Lines = true && this.isSetLines();
    boolean that_present_Lines = true && that.isSetLines();
    if (this_present_Lines || that_present_Lines) {
      if (!(this_present_Lines && that_present_Lines))
        return false;
      if (!this.Lines.equals(that.Lines))
        return false;
    }

    boolean this_present_Nodes = true && this.isSetNodes();
    boolean that_present_Nodes = true && that.isSetNodes();
    if (this_present_Nodes || that_present_Nodes) {
      if (!(this_present_Nodes && that_present_Nodes))
        return false;
      if (!this.Nodes.equals(that.Nodes))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_Lines = true && (isSetLines());
    list.add(present_Lines);
    if (present_Lines)
      list.add(Lines);

    boolean present_Nodes = true && (isSetNodes());
    list.add(present_Nodes);
    if (present_Nodes)
      list.add(Nodes);

    return list.hashCode();
  }

  @Override
  public int compareTo(Topology other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetLines()).compareTo(other.isSetLines());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLines()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.Lines, other.Lines);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetNodes()).compareTo(other.isSetNodes());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetNodes()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.Nodes, other.Nodes);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("Topology(");
    boolean first = true;

    sb.append("Lines:");
    if (this.Lines == null) {
      sb.append("null");
    } else {
      sb.append(this.Lines);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("Nodes:");
    if (this.Nodes == null) {
      sb.append("null");
    } else {
      sb.append(this.Nodes);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TopologyStandardSchemeFactory implements SchemeFactory {
    public TopologyStandardScheme getScheme() {
      return new TopologyStandardScheme();
    }
  }

  private static class TopologyStandardScheme extends StandardScheme<Topology> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, Topology struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // LINES
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list0 = iprot.readListBegin();
                struct.Lines = new ArrayList<TopoLine>(_list0.size);
                TopoLine _elem1;
                for (int _i2 = 0; _i2 < _list0.size; ++_i2)
                {
                  _elem1 = new TopoLine();
                  _elem1.read(iprot);
                  struct.Lines.add(_elem1);
                }
                iprot.readListEnd();
              }
              struct.setLinesIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // NODES
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list3 = iprot.readListBegin();
                struct.Nodes = new ArrayList<TopoNode>(_list3.size);
                TopoNode _elem4;
                for (int _i5 = 0; _i5 < _list3.size; ++_i5)
                {
                  _elem4 = new TopoNode();
                  _elem4.read(iprot);
                  struct.Nodes.add(_elem4);
                }
                iprot.readListEnd();
              }
              struct.setNodesIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, Topology struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.Lines != null) {
        oprot.writeFieldBegin(LINES_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.Lines.size()));
          for (TopoLine _iter6 : struct.Lines)
          {
            _iter6.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      if (struct.Nodes != null) {
        oprot.writeFieldBegin(NODES_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.Nodes.size()));
          for (TopoNode _iter7 : struct.Nodes)
          {
            _iter7.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TopologyTupleSchemeFactory implements SchemeFactory {
    public TopologyTupleScheme getScheme() {
      return new TopologyTupleScheme();
    }
  }

  private static class TopologyTupleScheme extends TupleScheme<Topology> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, Topology struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetLines()) {
        optionals.set(0);
      }
      if (struct.isSetNodes()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetLines()) {
        {
          oprot.writeI32(struct.Lines.size());
          for (TopoLine _iter8 : struct.Lines)
          {
            _iter8.write(oprot);
          }
        }
      }
      if (struct.isSetNodes()) {
        {
          oprot.writeI32(struct.Nodes.size());
          for (TopoNode _iter9 : struct.Nodes)
          {
            _iter9.write(oprot);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, Topology struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TList _list10 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.Lines = new ArrayList<TopoLine>(_list10.size);
          TopoLine _elem11;
          for (int _i12 = 0; _i12 < _list10.size; ++_i12)
          {
            _elem11 = new TopoLine();
            _elem11.read(iprot);
            struct.Lines.add(_elem11);
          }
        }
        struct.setLinesIsSet(true);
      }
      if (incoming.get(1)) {
        {
          org.apache.thrift.protocol.TList _list13 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.Nodes = new ArrayList<TopoNode>(_list13.size);
          TopoNode _elem14;
          for (int _i15 = 0; _i15 < _list13.size; ++_i15)
          {
            _elem14 = new TopoNode();
            _elem14.read(iprot);
            struct.Nodes.add(_elem14);
          }
        }
        struct.setNodesIsSet(true);
      }
    }
  }

}

